"""Contains the ChatAgent class, responsible for managing the chat agent's interactions
with the language model and tools. It provides methods for streaming chat responses
and resuming after tool interrupts.
"""

from collections.abc import AsyncIterator, Sequence
from typing import Any

from langchain.agents import create_agent
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import BaseMessage
from langchain_core.tools import BaseTool
from langgraph.checkpoint.base import BaseCheckpointSaver
from langgraph.types import Command

from src.llm.judge import AnswerJudge


class ChatAgent:
    def __init__(
        self,
        model: str | BaseChatModel,
        tools: Sequence[BaseTool],
        system_prompt: str,
        checkpointer: BaseCheckpointSaver,
        judge: AnswerJudge,
    ) -> None:

        self.agent = create_agent(
            model=model,
            tools=tools,
            system_prompt=system_prompt,
            checkpointer=checkpointer,
        )
        self.judge = judge

    async def stream(
        self, messages: Sequence[BaseMessage], thread_id: str
    ) -> AsyncIterator[dict[str, Any]]:
        """Main method for streaming chat responses.

        It takes a sequence of messages and a thread ID, and yields chunks of the
        response as they are generated by the language model. Once the agent's turn
        is done, the accumulated answer is passed through the judge (grounding +
        policy compliance) and its verdict is yielded as a final "judge" event -
        the answer itself is not held back or altered, the judge only flags issues.
        """
        full_answer = ""
        context_parts: list[str] = []

        async for event in self.agent.astream_events(
            {"messages": list(messages)},
            version="v2",
            config={
                "configurable": {
                    "thread_id": thread_id,
                }
            },
        ):
            event_type = event.get("event")

            # Handle different event types and yield appropriate responses

            # Handle tool start events
            if event_type == "on_tool_start":
                tool_name = event.get("name", "tool")
                tool_input = event.get("data", {}).get("input")
                content = f"Tool-Aufruf: {tool_name}"

                if tool_input:
                    content += f" ({tool_input})"

                yield {
                    "type": "tool",
                    "content": content,
                    "name": tool_name,
                    "input": tool_input,
                    "run_id": event.get("run_id"),
                }

            # Handle tool completion, so callers can see what a tool returned
            # (not just that it started) without re-deriving it elsewhere.
            elif event_type == "on_tool_end":
                output = event.get("data", {}).get("output")

                # A tool that writes to graph state (e.g. save_user_name) returns
                # a Command instead of a plain ToolMessage - Command isn't JSON
                # serializable, so pull its ToolMessage content out instead.
                if isinstance(output, Command):
                    command_messages = output.update.get("messages", [])
                    output = command_messages[0] if command_messages else None

                tool_output = getattr(output, "content", output)
                if isinstance(tool_output, str):
                    # Grounding material for the judge - whatever a tool returned
                    # to the model is what the final answer is allowed to rely on.
                    context_parts.append(tool_output)

                yield {
                    "type": "tool_result",
                    "name": event.get("name", "tool"),
                    "output": tool_output,
                    # Structured data for tools using response_format=
                    # "content_and_artifact" (e.g. search_versicherungsbedingungen) -
                    # lets a UI render results itself instead of parsing `output`.
                    "artifact": getattr(output, "artifact", None),
                    "run_id": event.get("run_id"),
                }

            # Handle tool interrupts
            elif event_type == "on_chain_stream":
                chunk = event.get("data", {}).get("chunk", {})
                interrupts = chunk.get("__interrupt__", []) if isinstance(chunk, dict) else []

                if interrupts:
                    interrupt = interrupts[0]
                    interrupt_value = getattr(interrupt, "value", {})
                    action_requests = interrupt_value.get("action_requests", [])

                    yield {
                        "type": "interrupt",
                        "interrupt_id": getattr(interrupt, "id", ""),
                        "action_requests": action_requests,
                    }
            # Handle chat model stream events
            elif event_type == "on_chat_model_stream":
                chunk = event.get("data", {}).get("chunk")
                content = getattr(chunk, "content", "")

                if content:
                    text = content[0]["text"]
                    full_answer += text
                    yield {"type": "ai", "content": text}

        if full_answer:
            raw_query = messages[-1].content if messages else ""
            query = raw_query if isinstance(raw_query, str) else str(raw_query)
            verdict = self.judge.review(
                query=query,
                context="\n\n".join(context_parts),
                answer=full_answer,
            )
            yield {
                "type": "judge",
                "passed": verdict.passed,
                "issues": verdict.issues,
            }

    # FUTURE: This will not happen in the current version of the agent, because there is no HITL gate yet.
    async def resume(
        self,
        thread_id: str,
        interrupt_id: str,
        decisions: list[dict[str, Any]],
    ) -> AsyncIterator[dict[str, Any]]:
        """Resumes a chat after a tool interrupt.

        It takes a thread ID, an interrupt ID, and the decision made by the user,
        and yields chunks of the response as they are generated by the language model.
        """
        async for event in self.agent.astream_events(
            Command(resume={interrupt_id: {"decisions": decisions}}),
            version="v2",
            config={
                "configurable": {
                    "thread_id": thread_id,
                }
            },
        ):
            event_type = event.get("event")

            if event_type == "on_tool_start":
                tool_name = event.get("name", "tool")
                tool_input = event.get("data", {}).get("input")
                content = f"Tool-Aufruf: {tool_name}"

                if tool_input:
                    content += f" ({tool_input})"

                yield {"type": "tool", "content": content}

            elif event_type == "on_chat_model_stream":
                chunk = event.get("data", {}).get("chunk")
                content = getattr(chunk, "content", "")

                if content:
                    yield {"type": "ai", "content": content[0]["text"]}
